### PR TITLE
Badge better links

### PR DESCRIPTION
**Pull request by Neustradamus**
Badge better links
It permits to have the xmpp.net at left part, client link on C2S part and server link on S2S part
- https://xmpp.net/
- https://xmpp.net/result.php?domain=domain.tld&type=client
- https://xmpp.net/result.php?domain=domain.tld&type=server

### CODE REVIEW

**Comment by Neustradamus** [comment]
Dear @guusdk, @horazont: After several months, any news?

**Comment by Neustradamus** [comment]
1 year and 6 months after: Any news?

**Comment by Neustradamus** [comment]
@mwild1: Can you look?

**Comment by mwild1** [comment]
Belated thanks for the PR! However this project is no longer being maintained (as you probably gathered already). It has more fundamental issues that were unresolved for a long time.

We no longer run it at xmpp.net, and I'm in the process of archiving the unmaintained repositories.

**Pull request closed without merging**
